/* Generated by automated build script */
#define RELEASE 0.70
#define TEXTVER "Release 0.70"
#define SSHVER "PuTTY-Release-0.70"
#define BINARY_VERSION 0,70,0,0
#define SOURCE_COMMIT "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
