/* Generated by automated build script */
#define RELEASE 0.70-3
#define TEXTVER "Release 0.70-3"
#define SSHVER "PuTTY-Release-0.70-3"
#define BINARY_VERSION 0,70,0,3
#define SOURCE_COMMIT "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
