/* Generated by automated build script */
#define RELEASE 0.69
#define TEXTVER "Release 0.69-1"
#define SSHVER "PuTTY-Release-0.69-1"
#define BINARY_VERSION 0,69,0,1
#define SOURCE_COMMIT "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"
