#ifndef PUTTY_PUTTYTAB_RC_H
#define PUTTY_PUTTYTAB_RC_H

#define IDI_PUTTYTAB 101
#define IDD_COMMAND_LINE 102
#define IDD_RENAME_TAB 103
#define IDC_TEXT_VALUE 1001
#define IDC_CONNECT_SESSION 1002
#define IDC_CONNECT_BUTTON 1003

#define IDM_FILE_NEW 101
#define IDM_FILE_ARGUMENTS 102
#define IDM_FILE_DUPLICATE 103
#define IDM_FILE_CLOSE 104
#define IDM_FILE_CLOSE_OTHERS 105
#define IDM_FILE_CLOSE_ALL 106
#define IDM_FILE_EXIT 107

#define IDM_SESSION_LOG 201
#define IDM_SESSION_RECONFIGURE 202
#define IDM_SESSION_RESTART 203
#define IDM_SESSION_COPY 204
#define IDM_SESSION_PASTE 205
#define IDM_SESSION_COPY_ALL 206
#define IDM_SESSION_CLEAR_SCROLLBACK 207
#define IDM_SESSION_RESET 208
#define IDM_SESSION_HELP 209
#define IDM_SESSION_ABOUT 210
#define IDM_SESSION_RENAME 211
#define IDM_SESSION_RESET_NAME 212
#define IDM_SESSION_LOCK 213
#define IDM_SESSION_MOVE_LEFT 214
#define IDM_SESSION_MOVE_RIGHT 215

#define IDM_VIEW_NEXT 301
#define IDM_VIEW_PREVIOUS 302
#define IDM_VIEW_ALWAYS_ON_TOP 303
#define IDM_VIEW_FULLSCREEN 304
#define IDM_VIEW_STATUS_BAR 305
#define IDM_VIEW_CONNECT_BAR 306

#define IDM_SAVED_SESSION_FIRST 45000
#define IDM_SAVED_SESSION_LAST 49095

#endif
