/* Generated by automated build script */
#define RELEASE 0.76
#define TEXTVER "Release 0.76-1"
#define SSHVER "-Release-0.76-1"
#define BINARY_VERSION 0,76,0,1
#define SOURCE_COMMIT "See https://github.com/NoMoreFood/putty-cac"
