/* Generated by automated build script */
#define RELEASE 0.78
#define TEXTVER "Release 0.78"
#define SSHVER "-Release-0.78"
#define BINARY_VERSION 0,78,0,0
#define SOURCE_COMMIT "See https://github.com/NoMoreFood/putty-cac"
